### PR TITLE
Change single quotes to backticks

### PR DESCRIPTION
**Pull request by texastoland**

### CODE REVIEW

**Comment by nwolverson** [comment]
Why? What do back ticks mean in PureScript source?

Single quotes delimit character literals.

(And it's annoying to have them match when typing primed identifiers, for sure - but then auto closing quotes are usually not what I want in general)

**Comment by texastoland** [comment]
> Why? What do back ticks mean in PureScript source?

Infix functions. I want to be able to insert them around the selected word.

> Single quotes delimit character literals.

I've literally never used them whereas I avoid primed identifiers but still use them quite often. It's even more annoying because backspace is also <q>smart</q> making it downright difficult for the overwhelmingly common use case.

**Comment by nwolverson** [comment]
Oh the infix thing, completely spaced on that. Yes I agree, better to make the change. Better if the editor didn't do it at the end of words...

**Comment by texastoland** [comment]
Thanks for everything 🙏

**Pull request merged**
